### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by beenje** [silx-kit/freesas#90]
Hello,
Latest release 0.9.0 is from 2021. I have issues rebuilding it with newer versions of python on conda-forge (due to some outdated setuptools usage in setup.py).
I see that build system was changed to `mesonpy` a while ago and that `numpy` 2 support was added recently. Would it be possible to get a new release on pypi?

**Comment by kif** [comment]
Makes sense !

**Comment by kif** [comment]
Available on pypi: https://pypi.org/project/freesas/2024.9.0/
The doc is on silx: http://www.silx.org/doc/freesas/2024.09/
